function [result] = ml_egomaps_compute(...
    animal_pos_x_cm, animal_pos_y_cm, animal_facing_angle_deg, ...
    cell_activation, ...
    ARENA_WIDTH_CM, ARENA_HEIGHT_CM, RADIUS_CM, EGOMAPS_CM_PER_BIN, showAnimation)

    DISCRETIZATION_SCALE_FACTOR = 100;
    EgoTable = ml_egomaps_compute_segment_table(...
        animal_pos_x_cm, animal_pos_y_cm, animal_facing_angle_deg, ...
        ARENA_WIDTH_CM, ARENA_HEIGHT_CM, RADIUS_CM, ...
        DISCRETIZATION_SCALE_FACTOR);
    
    result = ml_egomaps_compute_with_egotable(...
    animal_pos_x_cm, animal_pos_y_cm, animal_facing_angle_deg, ...
    cell_activation, ...
    ARENA_WIDTH_CM, ARENA_HEIGHT_CM, RADIUS_CM, EGOMAPS_CM_PER_BIN, EgoTable, showAnimation);
end % function